name: CI
on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{ secrets.name }}
  
  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{ secrets.name }}
